name: DataStructuresPackage

on:
  pull_request:
    branches: [ "MdEditor_CI_Input_Turulin" ]

jobs: 
  build:
    name: Test DataStructuresPackage
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd Packages/DataStructuresPackage
          swift build -v
      - name: Run tests
        run: |
          cd Packages/DataStructuresPackage
          swift test -v