name: DataStructuresPackage

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    steps:
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd Packages/DataStructuresPackage
          swift build -v
      - name: Run tests
        run: |
          cd Packages/DataStructuresPackage
          swift test -v
