name: TaskManagerPackage

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    steps:
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd Packages/TaskManagerPackage
          swift build -v
      - name: Run tests
        run: |
          cd Packages/TaskManagerPackage
          swift test -v
